name: "Prod :: Terraform :: Destroy"

on: workflow_dispatch

jobs:
  terraform-destroy:
    name: "Destroy"
    runs-on: ubuntu-latest
    env:
      cwd: ./packages/terraform/main/prod
      lambda_cwd: ./packages/lambda
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.3.4

      - name: "Setup - Build AWS Credentials"
        run: |
          mkdir -p ~/.aws
          echo "[${{ secrets.PROD_TF_VAR_AWS_PROFILE }}]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.PROD_TF_VAR_AWS_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.PROD_TF_VAR_AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: "Setup - Node"
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1.3.2

      - name: "Run - Build Lambda Functions"
        working-directory: ${{ env.lambda_cwd }}
        run: |
          npm install
          npm run build

      - name: "Run - Terraform Init"
        working-directory: ${{ env.cwd }}
        run: terraform init -input=false

      - name: "Run - Terraform Destroy"
        working-directory: ${{ env.cwd }}
        id: plan
        run: terraform destroy -auto-approve
        env:
          TF_VAR_aws_region: ${{ secrets.PROD_TF_VAR_AWS_REGION }}
          TF_VAR_aws_profile: ${{ secrets.PROD_TF_VAR_AWS_PROFILE }}
          TF_VAR_aws_access_key: ${{ secrets.PROD_TF_VAR_AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_access_key: ${{ secrets.PROD_TF_VAR_AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_secret_access_key_do_encrypted: ${{ secrets.PROD_TF_VAR_AWS_SECRET_ACCESS_KEY_DO_ENCRYPTED }}
          TF_VAR_do_token: ${{ secrets.PROD_TF_VAR_DO_TOKEN }}
          TF_VAR_facebook_client_id: ${{ secrets.PROD_TF_VAR_FACEBOOK_CLIENT_ID }}
          TF_VAR_facebook_client_secret: ${{ secrets.PROD_TF_VAR_FACEBOOK_CLIENT_SECRET }}
          TF_VAR_google_client_id: ${{ secrets.PROD_TF_VAR_GOOGLE_CLIENT_ID }}
          TF_VAR_google_client_secret: ${{ secrets.PROD_TF_VAR_GOOGLE_CLIENT_SECRET }}
          TF_VAR_cloudinary_cloud_name: ${{ secrets.PROD_TF_VAR_CLOUDINARY_CLOUD_NAME }}
          TF_VAR_cloudinary_key: ${{ secrets.PROD_TF_VAR_CLOUDINARY_KEY }}
          TF_VAR_cloudinary_secret_key: ${{ secrets.PROD_TF_VAR_CLOUDINARY_SECRET_KEY }}
          TF_VAR_cloudinary_secret_key_do_encrypted: ${{ secrets.PROD_TF_VAR_CLOUDINARY_SECRET_KEY_DO_ENCRYPTED }}
          TF_VAR_database_url: ${{ secrets.PROD_TF_VAR_DATABASE_URL }}
          TF_VAR_database_url_do_encrypted: ${{ secrets.PROD_TF_VAR_DATABASE_URL_DO_ENCRYPTED }}
          TF_VAR_github_personal_access_token: ${{ secrets.PROD_TF_VAR_GITHUB_PERSONAL_ACCESS_TOKEN }}
          TF_VAR_aws_user_pool_id: ${{ secrets.PROD_TF_VAR_AWS_USER_POOL_ID }}
          TF_VAR_aws_user_pool_client_id: ${{ secrets.PROD_TF_VAR_AWS_USER_POOL_CLIENT_ID }}
          TF_VAR_user_pool_name: ${{ secrets.PROD_TF_VAR_USER_POOL_NAME }}
          TF_VAR_client_name: ${{ secrets.PROD_TF_VAR_CLIENT_NAME }}
